# -*- coding: utf-8 -*-
"""PDF2AUDIOAPP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RKXNVVEV8fmpveUE8roW9M4oEnvwydE
"""

import streamlit as st
from PyPDF2 import PdfReader
import pyttsx3
import os

# Create a temporary directory if it doesn't exist
temp_dir = "temp"
os.makedirs(temp_dir, exist_ok=True)

st.title("PDF to Audio Converter")

uploaded_file = st.file_uploader("Choose a PDF file", type="pdf")

def pdf_to_audio(pdf_path, language="es-ES"):
    reader = PdfReader(pdf_path)
    text = ""
    for page in reader.pages:
        text += page.extract_text()

    engine = pyttsx3.init()
    voices = engine.getProperty('voices')

    # Set to Spanish voice if available
    for voice in voices:
        if "Spanish" in voice.name:
            engine.setProperty('voice', voice.id)
            break
    else:
        st.warning("Spanish voice not found, using default voice.")

    audio_file_path = os.path.join(temp_dir, "audio.mp3")
    engine.save_to_file(text, audio_file_path)
    engine.runAndWait()

    return audio_file_path

if uploaded_file is not None:
    # Save the uploaded PDF file
    pdf_path = os.path.join(temp_dir, uploaded_file.name)
    with open(pdf_path, "wb") as f:
        f.write(uploaded_file.getbuffer())

    # Convert PDF to audio
    audio_path = pdf_to_audio(pdf_path)

    # Provide a download link for the audio file
    with open(audio_path, "rb") as f:
        st.download_button("Download Audio", data=f, file_name="audio.mp3")